# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e8cc87b42d3d34e91bbf62153043ef41e8bd356b280c1345275d80da4953f7d23fa5e80d5392bb09b311275a4a2f7d4a776458aa7125d293f0943c768bf00ee

test:
  secret_key_base: d78822488a430c013f8d7303f0b482ac9f259e20fa244b61b4489bc85b66bbdf0a1644c59275dda4145706bdcff29548d4ce096e272890e2b0b4f73d0f2b0641

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
